# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.3.0

    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: npm install --force
